* Mainstream vs. plurale Ökonomie
In der Volkswirtschaftslehre (VWL) gibt es einen Konflikt zwischen "Mainstream"-Ökonomen und "pluralen Ökonomen". Mit Mainstream ist hier das vorherrschende Paradigme in der VWL gemeint, die neoklassische Theorie. Sie kennzeichnet sich durch bestimmte Grundsätze aus, wie zum Beispiel:
- *Grenznutzentheorie*: Der Grenznutzen eines Gutes ist der Nutzen, den ein Wirtschaftsubjekt durch Konsum des Gutes erfährt. Dabei wird das Gesetz vom abnehmenden Grenznutzen angenommen: mit jedem weiteren Konsum eines Gutes nimmt der Nutzen, der aus dem Konsum gezogen wird, ab. Der Grenznutzen bestimmt in der neoklassischen Theorie den Preis eines Gute und damit seinen Wert. Dies steht im Gegensatz zu den klassischen Theorien, in denen der Wert eines Gutes über andere Dinge definiert wurde.
- *Homo Oeconomicus*: Der Homo Oeconomicus ist ein Modell für individuelle Wirtschaftssubjekte, das annimmt, das jedes Subjekt als rationaler Agent seinen eigenen Nutzen (wie auch immer definiert) versucht, zu maximieren. Dabei ist die Definition des Nutzen flexibel und kann zum Beispiel auch altruistische Komponenten beinhalten.
- 

Die pluralen Ökonomen kritisieren die neoklassische Theorie an mehreren Punkten, wie zum Beispiel:
- Menschen verhalten sich nicht wie der Homo Oeconomicus. Stattdessen gibt es viele Beispiele, in denen sich Menschen irrational verhalten.
- Die neoklassische Theorie geht davon aus, dass wir in einer Welt leben (einem Ökosystem), dessen Größe die der Wirtschaft so sehr übersteigt, dass die Grenzen des Ökosystems keine Rolle für die Wirtschaft spielen (siehe Herman Daly, Dougnut Economics). Wir leben sozusagen in einer leeren Welt. Dies war vor 100 Jahren zutreffend, als die Weltbevölkerung und die Weltwirtschaft um eine Vielfaches kleiner war als heute. Heutzutage hat die Menschheit mehrere planetare Grenzen (siehe Doughnut Economics) bereits überschritten, d.h. wir leben heute in einer vollen Welt.
- Die neoklassische Theorie behauptet, keine normative Theorie, sondern stattdessen eine streng objektive, empirische Theorie zu sein. Die pluralen Ökonomen bestreiten diese Einstellung und behaupten, dass auch die Neoklassik normative Annahmen macht.

** Bachmann im "In der Wirtschaft" podcast:
   - der Mainstream ist schon plural: es gibt viele verschiedene Methoden und auch konzeptionell bietet der Mainstream genügend Platz für Ideen
   - alternative Ideen müssen und können sich durchsetzen, siehe Umweltökonomie (Nordhaus und Co.), Gender Studies, die haben es auch geschafft
   - Forschung in den Wirtschaftswissenschaften muss konstruktive etwas zum Verständnis beitragen, dann gibt es auch einen Platz für sie
   - "Ich will in erster Linie die Welt verstehen, nicht die Welt verändern" --> Gegensatz zu Raworth: Wirtschaftswissenschaften als beschreibende (empirische) Wissenschaft vs. Ökonomen als Ingenieure des Wirtschaftssystems, die normativ arbeiten
   - die VWL stellt Theorien auf, die unter bestimmten Annahmen gültig sind. Solange die Annahmen klar erklärt sind und die Mathematik stimmt, ist das so in Ordnung und es besteht kein Problem.
** Eigene Notizen
   - vielleicht ist der Grundkonflikt einfach eine andere Auffassung davon, was Ökonomen leisten sollen: Wirtschaftswissenschaften als beschreibende (empirische) Wissenschaft vs. Ökonomen als Ingenieure des Wirtschaftssystems, die normativ arbeiten
   - der Standpunkt, dass es in Ordnung ist, wenn die VWL mit stark vereinfachenden Modellen arbeitet, solange die Vereinfachungen klar formuliert sind, macht es sich ein bisschen zu einfach. Denn Ökonomen sind meist nicht nur Wissenschaftler, sondern drängen in die Öffentlichkeit, indem sie eigene Medienbeiträge produzieren (Zeitungskolumnen, Interviews, Podcasts etc.), mit denen sie Einfluss nehmen wollen, oder indem sie als Politikberater auftreten. In beiden Fällen werden die vereinfachenden Theorien in die Sphäre der POlit
   - Es gibt Unterschied zu anderen Wissenschaften wie der Physik 
   - meine Hauptfrage: was ist die Antwort der Ökonomen auf die Umweltprobleme: erschöpft sich alles im CO2-Preis?
* Umweltökonomie (Environmental economics)
  Die Umweltökonomie beschäftigt sich mit den Wechselwirkungen zwischen der Wirtschaft und der Umwelt mit ihren (knappen) Resourcen.
  Das *Ausgangsproblem* ist, dass Umweltressourcen durch Überbeanspruchung knapper werden, dabei jedoch weiterhin als öffentliches Gut im Besitz aller und damit zur freien Verfügung stehend aufgefasst werden. Dadurch entsteht ein Unterschied zwischen privaten (Kosten des Verbrauchers) und gesellschaftlichen (Kosten der Gesellschaft) Kosten. Beispiel ist die Aufnahmekapazität von Treibhausgasen in der Atmosphäre.
  Das *Ziel der neoklassischen Umweltökonomie* ist es, eine optimale Umweltbelastung zu erreichen, d.h. eine Belastung, bei der der Grenznutzen der Umweltbelastungen gerade noch die Grenzschäden rechtfertigt.
  *Aufgaben*: Entwicklung von Instrumenten zur Marktintegration natürlicher Resourcen in die Entscheidungsverfahren für öffentliche und private Umwelteingriffe
  *Lösungsansätze*: der neoklassische Lösungsansatz besteht darin, die Externalitäten (Umweltschäden) zu internalisieren, das heißt in die wirtschaftliche Rechnung einzupreisen. Die Idee ist: erst wenn die Marktpreise die wahren Kosten beinhalten, wird die Knappheit und Kostbarkeit der natürlichen Resourcen bewusst und kann berücksichtigt werden.
** Coase-Theorem
   Das Coase-Theorem besagt, dass wenn zwei Verhandlungspartner, der Schädiger und Geschädigte, miteinander verhandeln und folgende Annahmen erfüllt sind:
   - keine Transaktionkosten für die Verhandlungen
   - Vollständige Informationen
   - Verfügungsrechte
   Dann kann ein Verhandlungsergebnise erzielt werden, indem die Schäden und Nutzen optimal ausbalanciert werden. Dieses Gleichgewicht ist erreicht, wenn die Grenzschadenskosten gleich den Grenzvermeidungskosten sind.
   der Umweltökonomie entgegen steht die ökologische Ökonomie, die den Ansatz der Umweltökonomie, die Umwelt in den Markt zu integrieren, ablehnt.
** Nordhaus: Climate Clubs, DICE model
*** DICE model
    Ein IAM (Integrated assessement model), das sich mit dem Wechselspiel von Klimwandel und ökonomischem Wachstum beschäftigt. Ziel ist es, eine optimale Politik vorherzusagen, d.h. eine Politik, die das wirtschaftliche Wachstum optimiert. So sagt es zum Beispiel ein optimales Temperaturziel oder einen optimalen CO2-Preis voraus.
    Das Modell sagt zum Beispiel auch einen "Social Cost of Carbon" voraus, d.h. die Kosten, die durch die Emission von einer Tonne CO2 in die Atmosphäre entstehen. Diese bilden die Grundlage für eine CO2-Steuer.
*** Climate Clubs
    Die Idee: Anstelle von weltumfassenden Klimaabkommen, die zum großen Teil auf Freiwilligkeit beruhen, sollen Climate Clubs treten. Dies sind Klubs, die von mehreren Staaten gebildet werden. Diese Staaten einigen sich auf einen gemeinsamen CO2-Preis (kein Temperaturziel) und bestragen Nicht-Mitglieder, indem sie Zölle erheben.
