* Green New Deal (Ann Pettifor)
  Der Green New Deal, der von Pettifor mit Anderen nach der Finanzkrise 2008 entwickelt wurde, hat zum Ziel, das gegenwärtige System so umzubauen, dass die Größe des Wirtschaftssystems der verfügbaren Kapatität des Ökosystems entspricht ("Steady State Economy"). Um dies zu erreichen, werden große Anstrengungen und große Investitionen nötig sein. Diese Investitionen sollen dadurch erreicht werden, dass die Geldströme in nachhaltige Industrien umgeleitet werden ("Den Kampf mithilfe des Finanzsystems gewinnen"). Außerdem plädiert Pettifor dafür, dass nationale Wirtschaftssysteme wieder eigenständiger werden, d.h. der Freihandel soll massiv zurückgedrängt werden.

Die Vision des GND für die Wirtschaft beinhaltet sieben Prinzipien:
1. *Steady state economy*
    Eine "Steady state economy" nach Herman Daly ist eine Wirtschaft, die weder wächst noch schrumpft, sondern deren Größe der Kapazität des Ökosystems entspricht. Zugrunde liegend ist die Erkenntnis, dass eine Wirtschaft, die in im endlichen Ökosystem der Erde eingebettet ist, nicht endlos wachsen kann. Dabei wird zwischen quantiativem Wachstum und qualitativer Entwicklung unterschieden. Ersteres muss begrenzt werden, zweiteres ist positiv und muss erhalten werden.
2. *Begrenzte Bedürfnisse, nicht grenzenlose Begierden*
   Der GND definiert die folgenden Grundbedürfnisse, die Vorrang gegenüber den Begierden haben, welche zu grenzenlosem Konsum führen und daher schädlich sind:
   Gesundheitsversorgung, Lebensmittel und Wasser, eine schützende Unterkunft, ein sicheres alltägliches und berufliches Umfeld, eine sichere Kindheit, bedeutungsvolle primäre Beziehungen, physische Sicherheit, ökonomische Sicherheit, sichere Geburtenkontrolle und Geburten, Grundbildung.
3. *Selbstversorgung*
   Nationale Volkswirtschaften sollten die Bedürfnisse ihrer Bürger selbst erfüllen können und weniger auf Handel mit anderen Nationen angewiesen sein, als es zur Zeit der Fall ist. Das bedeutet konkret, dass Industrien, die im eigenen Land angesiedelt werden können, auch dort existieren sollen (Beispiel: Textilindustrie).
4. *Eine gemischte Volkswirtschaft*
   In der idealen Volkswirtschaft das GND übernimmt der Staat die Aufgaben, die sich am besten für kollektives Handeln eignen, während der Markt die Versorgung mit Gütern und Dienstleistungen erleichtert, die innerhalb des stationären Rahmens zu Verfügung gestellt werden.
   Konkret: Der Staat investiert in große Transformationsprojekte, z.B. Ankauf und Aufforstung weiterer Gebiete, öffentlichen Verkehr oder Umrüstung von Gebäuden. Von diesen Investitionen profieren lokale Bauunternehmen und Betriebe, die die konkreten Aufgaben dann übernehmen.
5. *Eine arbeitskraftintensive Wirtschaft*
   In der Wirtschaft des GND werden viele Aufgaben, die zur Zeit von fossilen Energien erledigt werden, von erneuerbaren Energien erledigt. Wo dies nicht möglich ist, werden mehr Arbeitskräfte benötigt werden. Durch die hohen öffentlichen Investitionen zur Transformation des Wirtschaftssystem werden viele qualifizierte Arbeitsplätze entstehen. Ziel ist es, sinnvolle Tätigkeiten zu schaffen und die "obszönen Ungleichheiten" zu beseitigen, die den gegenwärtigen Kapitalismus auszeichnen.
6. *Geldpolitische und fiskalische Koordinierung für eine stationäre Wirtschaft*
   Pettifor favorisiert eine Keynesianische Geld- und Fiskalpolitik: Investitionen des Staates führen zu Wirtschaftswachstum, Beschäftigung und dadurch zu Steuereinnahmen. Es ist also nicht so, dass Steuern die Investitionen des Staates finanzieren, sondern umgekehrt entstehen Steuern durch Investitionen.
   Sie stellt sich explizit gegen die Sichtweise, dass CO2-Steuern das Allheilmittel sind, um Geldströme von fossilen in erneuerbare Industrien umzuleiten. Stattdessen sollte der Staat zuerst aktiv werden und Alternativen zu fossilen Industrien fördern. Sobald diese Alternativen da sind, könnten CO2-Steuern dann sinnvoll sein, um Anreize für bestimmte Verhaltensweisen zu schaffen. Das Problem mit CO2-Steuern u.ä. ist jedoch im Allgemeinen, dass sie meist die Armen zuerst treffen und die Reichen eher wenig berühren, während die Reichen jedoch die meisten CO2-Emissionen verursachen.
7. *Die Illusion der unendlichen Expansion aufgeben*
   Die Volkswirtschaft des GND darf die Kapazität des Ökosystems, aber auch seine eigene Kapazität nicht überschreiten, denn das würde zu Inflation führen.

** Zusätzliche Punkte
*** Selbstversorgung, Beschränkung des Freihandels, eigenständige Staaten
Die Wirtschaft muss sich nach dem GND lokaliseren. Das heißt, dass der Freihandel entschieden zurückgedrängt werden muss. Zwei Hauptgründe hierfür werden angeführt:
- der weltweit zunehmende Austausch von Waren, auch über sehr lange Strecken, verursacht hohe Kosten auf Seiten der Umwelt durch Emissionen von Treibhausgasen und andere Effekte. Dazu kommt, dass vielfach gehandelte Waren nicht notwendigerweise importiert werden müssen (Beispiel: Äpfel in Deutschland aus Neuseeland, während Äpfel auch ebensogut in Deutschland und anderen europäischen Ländern angebaut werden können).
- noch freizügiger als der Austausch von physischen Waren ist der freie Verkehr von Geldmitteln. Dadurch, dass Finanzmittel größtenteils frei über Grenzen hinweg bewegt werden können, können Unternehmen ihre Investitionen leicht in andere Erdteile umleiten und damit Druckmittel auf demokratische Regierungen aufbauen. So entsteht ein "Race to the bottom" bei Arbeits-, Sozial- und Umweltstandards.
Besonders die Bewegungsfreiheit von Finanzmitteln hat zu weltumspannenden Konzernen geführt, die teilweise mächtiger als die nationalen Regierungen scheinen, da sie sich auf globaler Bühne frei bewegen können, wo es keine demokratische Kontrolle gibt (die eben im Wesentlichen auf nationaler Bühne stattfindet).
Aus diesen Gründen plädiert Pettifor dafür, die nationalen Wirtschaften wieder eigenständiger zu gestalten. Die Produktion von wichtigen Gütern (Lebensmittel und essentielle Konsumgüter) soll jedes Land wieder selbst bewerkstelligen können. Interessanterweise verliert Pettifor kaum ein Wort zur EU, es ist also nicht ganz klar, ob sie die EU in diesem Sinne schon als "Land" sieht oder dafür plädiert, auch in Europa Macht von der EU zurück zu den einzelnen Länder zu verlagern und den europäischen Binnenmarkt wieder zurückzuentwickeln.
*** Gegen die MMT
    Pettifor stellt sich explizit gegen die Modern Monetary Theory (MMT), die davon ausgeht, dass die Zentralbanken Geld für die direkte Verteilung an Bürger oder zur Finanzierung von Staatsausgaben drucken können. Nach ihrem Verständnis Geld nur enstehen, indem Schulden gemacht werden, z.B. in Form von Verträgen, die die Rückzahlung garantieren, beispielsweise Anleihen. Zentralbanken können das dann finanzieren, indem sie Staatsanleihen der Regierung aufkaufen und dadurch die Zinsen auf die Anleihen senken. Staatsinvestitionen werden also durch Anleihen finanziert und durch deinen demokratischen Prozess von gewählten Vertretern entschieden.
Die MMT will das umgehen und stattdessen die Zentralbanken direkt entscheiden lassen, wieviel Geld die Wirtschaft benötigt. Pettifor kritisiert dies als undemokratisch und intransparent. Zum Zweiten kann diese Geldpolitik leicht zu enormer Inflation führen, zu wachsender Ungleichheit führen und zu Verzerrungen in der Wirtschaft führen.
Ein weiteres Argument gegen die MMT ist, dass sie eigentlich nur in den USA als Ausgeberin der weltweiten Leitwährung funktionieren kann, denn die USA können tatsächlich unbegrenzt Geld drucken, denn arme Länder müssen Waren aus den USA und anderen Ländern in Dollar kaufen und sich daher in Dollar verschulden.
*** Gegen "Degrowth" als Begriff
Pettifor möchte sich nicht mit dem Begriff "Degrowth" identifizieren. "Degrowth" als Negation von Wachstum verstärkt nur die Fixierung auf das Konzept des Wachstum. Besser sei es, ein positives Gegenkonzept, den Begriff der stationären Wirtschaft ("Steady State Economoy"), entgegenzusetzen.
** Offene Fragen
- Wie entsteht Inflation?
- Wie kann man die Kapazität einer Volkswirtschaft berechnen?
